wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: huggingface
    huggingface_version: 4.6.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    t:
      1:
      - 1
      - 11
      2:
      - 1
      - 11
      4: 3.6.13
      5: 0.10.31
      6: 4.6.1
      8:
      - 5
learning_rate:
  desc: null
  value: 0.01
